workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    FastAPI:
        inputs:
            - location: https://api.opper.ai/v2/openapi.json
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/opper/opper/fast-api
targets:
    opper:
        target: python
        source: FastAPI
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/opper/opper/fast-api-python-code-samples
            labelOverride:
                fixedValue: Python (SDK)
            blocking: false
